name: training github action
on: push
jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Install nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: install dependencies
              run: npm ci
            - name: lint test
              run: npm run lint
            - name: test project
              run: npm test
            - name: deploy
              run: npm run build